--- 
- uuid: d3d1838c-1820-11de-860a-001ec94098a1
  vendor_interface_id: 1
  id: 1
  config_string: _auto_
- uuid: d3db8120-1820-11de-860a-001ec94098a1
  vendor_interface_id: 2
  id: 2
  config_string: _auto_
- uuid: d3dbf1a0-1820-11de-860a-001ec94098a1
  vendor_interface_id: 3
  id: 3
  config_string: _auto_
- uuid: d3dc5956-1820-11de-860a-001ec94098a1
  vendor_interface_id: 4
  id: 4
  config_string: /dev/tty.PascoAirLink
- uuid: d3dc8764-1820-11de-860a-001ec94098a1
  vendor_interface_id: 4
  id: 5
  config_string: /dev/tty.PascoAirLink1
- uuid: d3dcefce-1820-11de-860a-001ec94098a1
  vendor_interface_id: 5
  id: 6
  config_string: none
- uuid: d3de58a0-1820-11de-860a-001ec94098a1
  vendor_interface_id: 6
  id: 7
  config_string: none
- uuid: d3dec222-1820-11de-860a-001ec94098a1
  vendor_interface_id: 7
  id: 8
  config_string: none
- uuid: d3df2e38-1820-11de-860a-001ec94098a1
  vendor_interface_id: 8
  id: 9
  config_string: _auto_
- uuid: d3dfbe02-1820-11de-860a-001ec94098a1
  vendor_interface_id: 9
  id: 10
  config_string: _auto_
- uuid: e26884a4-93fe-11de-9836-001ff3caa767
  vendor_interface_id: 10
  id: 11
  config_string: none
- uuid: e26893ea-93fe-11de-9836-001ff3caa767
  vendor_interface_id: 11
  id: 12
  config_string: none
- uuid: e268a1dc-93fe-11de-9836-001ff3caa767
  vendor_interface_id: 12
  id: 13
  config_string: none
- uuid: e268aede-93fe-11de-9836-001ff3caa767
  vendor_interface_id: 13
  id: 14
  config_string: none
- uuid: e268bf3c-93fe-11de-9836-001ff3caa767
  vendor_interface_id: 14
  id: 15
  config_string: none
